<template>
    <div id="content">
      <div class="page-body-wrapper">
        <section id="home" class="home">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <div class="main-banner">
                  <div class="d-sm-flex justify-content-between">
                    <div data-aos="zoom-in-up">
                      <div class="banner-title">
                        <h4 class="font-weight-medium">Selamat Datang,
                          Di Website XII RPL 1
                        </h4>
                      </div>
                      <small class="mt-3">Abdurohman | Ahmad Wahyudi | Ali Abdurrohman | Agist Syaukul
                        Zaziel | Ananto Bayu | Aldi Arifiana Putra | Cahya Haerudin | Dede
                        Kurniawan | Dince Nur Fitriyyah | Dinar Febriyanti | Fajar Budiman
                        | Fikri Khairul Shaleh | Gusty Fachta Pratama | Ima Mustika | Lita
                        Juniar | Muhammad Alfin Abiansyah | Muhammad Canang Prakarsa |
                        Muhammad Nanda Nugraha | Muhammad Ripa'i | Muhammad Iman Pirmansah
                        | Muhammad Saefudin | Nalendra Arya Putra Pratama | Naufal
                        Fadhillah | Novan Riski Ramadhan | Nurhidayah | Putri Wulandari |
                        Reishan Tridya Rafly | Rima Amelia | Riski Kurniawan | Robi
                        Anugrah Bhayangkara | Siti Komariah | Syelomita Agatha Manulang |
                        Tasya Latifatul Khoeriyah | Touvan Oktoviana | Tri Rahmatika |
                        Vanie Juniar Meidriani | Yanuar Eka Susila

                        <br>
                        <br>
                      </small>
                      <p class="font-weight-medium">Angkatan 6 (2018-2021), SMK Negeri 4 Kuningan</p>
                    </div>
                    <div class="col-md-6 mt-5 mt-lg-0">
                      <picture>
                        <source srcset="static/assets/images/header.webp" type="image/webp">
                        <source srcset="static/assets/images/header.png" type="image/png">
                        <img src="static/assets/images/header.png" alt="header" class="animated bounce img-fluid"
                          data-aos="zoom-in-up">
                      </picture>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="our-services" id="spesies">
          <div class="container">
            <div class="row">
              <div class="col-sm-12">
                <h5 class="text-dark">Beragam Macam</h5>
                <h3 class="font-weight-medium text-dark mb-5">Jenis Spesies</h3>
              </div>
            </div>
            <div class="row" data-aos="fade-up">
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/game.webp" type="image/webp">
                    <source srcset="static/assets/images/game.png" type="image/png">
                    <img src="static/assets/images/game.png" class="img-fluid" alt="Kang Game" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Game
                  </h6>
                  <p>Sedikit skillnya, banyak bacotnya
                  </p>
                </div>
              </div>
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/molor.webp" type="image/webp">
                    <source srcset="static/assets/images/molor.png" type="image/png">
                    <img src="static/assets/images/molor.png" class="img-fluid" alt="Kang Molor" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Molor
                  </h6>
                  <p>Melanjutkan bermimpi sampai mimpinya terwujud
                  </p>
                </div>
              </div>
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/jajan.webp" type="image/webp">
                    <source srcset="static/assets/images/jajan.png" type="image/png">
                    <img src="static/assets/images/jajan.png" class="img-fluid" alt="Kang Jajan" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Jajan
                  </h6>
                  <p>Terus jajan, walau duit pas-pasan
                  </p>
                </div>
              </div>
            </div>
            <div class="row" data-aos="fade-up">
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box  pb-lg-0" data-aos="fade-down" data-aos-easing="linear"
                  data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/ghibah.webp" type="image/webp">
                    <source srcset="static/assets/images/ghibah.png" type="image/png">
                    <img src="static/assets/images/ghibah.png" class="img-fluid" alt="Kang Ghibah" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Ghibah
                  </h6>
                  <p>Menilai orang lain, sampai lupa menilai diri sendiri
                  </p>
                </div>
              </div>
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box pb-lg-0" data-aos="fade-down" data-aos-easing="linear"
                  data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/selfie.webp" type="image/webp">
                    <source srcset="static/assets/images/selfie.png" type="image/png">
                    <img src="static/assets/images/selfie.png" class="img-fluid" alt="Kang Selfie" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Selfie
                  </h6>
                  <p>Meski tak percaya diri, tapi tetap berusaha selfie
                  </p>
                </div>
              </div>
              <div class="col-sm-4 text-center text-lg-left">
                <div class="services-box pb-0" data-aos="fade-down" data-aos-easing="linear" data-aos-duration="1500">
                  <picture>
                    <source srcset="static/assets/images/nonton.webp" type="image/webp">
                    <source srcset="static/assets/images/nonton.png" type="image/png">
                    <img src="static/assets/images/nonton.png" class="img-fluid" alt="Kang Nonton" data-aos="zoom-in">
                  </picture>
                  <h6 class="text-dark mb-3 mt-4 font-weight-medium">Kang Nonton
                  </h6>
                  <p>Para penikmat film bajakan
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="our-process" id="statistik">
          <div class="container">
            <div class="row">
              <div class="col-sm-12" data-aos="fade-up">
                <h5 class="text-dark">Statistik</h5>
                <h3 class="font-weight-medium text-dark">Statistik XII RPL 1</h3>
                <div class="container">
                  <div class="row pt-5 mt-5 pb-5 mb-5">
                    <div class="col-sm-3">
                      <div class="d-flex py-3 my-3 my-lg-0 justify-content-center" data-aos="fade-down">
                        <picture>
                          <source srcset="static/assets/images/laki.webp" type="image/webp">
                          <source srcset="static/assets/images/laki.png" type="image/png">
                          <img src="static/assets/images/group.png" class="img-fluid mr-3" alt="Murid">
                        </picture>
                        <div>
                          <h4 class="font-weight-bold text-dark mb-0"><span class="scVal">0</span></h4>
                          <h5 class="text-dark mb-0">Murid</h5>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="d-flex py-3 my-3 my-lg-0 justify-content-center" data-aos="fade-up">
                        <picture>
                          <source srcset="static/assets/images/laki.webp" type="image/webp">
                          <source srcset="static/assets/images/laki.png" type="image/png">
                          <img src="static/assets/images/laki.png" class="img-fluid mr-3" alt="Laki Laki">
                        </picture>
                        <div>
                          <h4 class="font-weight-bold text-dark mb-0"><span class="fpVal">0</span></h4>
                          <h5 class="text-dark mb-0">Laki Laki</h5>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="d-flex py-3 my-3 my-lg-0 justify-content-center" data-aos="fade-down">
                        <picture>
                          <source srcset="static/assets/images/cewe.webp" type="image/webp">
                          <source srcset="static/assets/images/cewe.png" type="image/png">
                          <img src="static/assets/images/cewe.png" class="img-fluid mr-3" alt="Perempuan">
                        </picture>
                        <div>
                          <h4 class="font-weight-bold text-dark mb-0"><span class="tMVal">0</span></h4>
                          <h5 class="text-dark mb-0">Perempuan</h5>
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-3">
                      <div class="d-flex py-3 my-3 my-lg-0 justify-content-center" data-aos="fade-down">
                        <picture>
                          <source srcset="static/assets/images/chat.webp" type="image/webp">
                          <source srcset="static/assets/images/chat.png" type="image/png">
                          <img src="static/assets/images/chat.png" class="img-fluid mr-3" alt="Bacotan">
                        </picture>
                        <div>
                          <h4 class="font-weight-bold text-dark mb-0"><span class="bPVal">0</span></h4>
                          <h5 class="text-dark mb-0">Bacotan</h5>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section class="our-projects" id="projects">
          <div class="container">
            <div class="row mb-5">
              <div class="col-sm-12">
                <div class="d-sm-flex justify-content-between align-items-center mb-2">
                  <h3 class="font-weight-medium text-dark ">Inilah Kami</h3>
                </div>
              </div>
            </div>
          </div>
          <div class="mb-5" data-aos="fade-up">
            <div class="owl-carousel-projects owl-carousel owl-theme">
              <div class="item" v-for="image in images" :key="image">
                <picture>
                  <source :srcset="image+'.webp'" type="image/webp">
                  <source :srcset="image+'.jpg'" type="image/jpg">
                  <img :src="image+'.jpg'" alt="Carousel" title="Inilah Kami" />
                </picture>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
</template>

<script>
export default {
  data(){
    return{
       images: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20"
      ].map((images) => `static/assets/images/carousel/${images}`),
    }
  }
}
</script>
