<template>
    <div id="footer">
      <footer class="footer">
        <div class="footer-top">
          <div class="container">
            <div class="row">
              <div class="col-sm-6">
                <address>
                  <p class="font-weight-bold">XII RPL 1</p>
                  <p>SMK Negeri 4 Kuningan</p>
                  <p class="mb-4">Jl. Cikeusik No.73, Cikeusik, Cidahu, Kabupaten Kuningan, Jawa Barat</p>
                </address>
              </div>
              <div class="col-sm-6">
                <div class="row">
                  <div class="col-sm-6">
                    <div class="social-icons">
                      <h6 class="footer-title font-weight-bold">
                        Sosial Media
                      </h6>
                      <div class="d-flex">
                        <a href="https://instagram.com/erpeelsantuy" target="_blank"><i
                            class="mdi mdi-instagram"></i></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-bottom">
          <div class="container">
            <div class="text-center">
              <picture>
                <source srcset="static/assets/images/erpeel.webp" type="image/webp">
                <source srcset="static/assets/images/erpeel.png" type="image/png">
                <img src="static/assets/images/erpeel.png" alt="Logo RPL" class="mr-3" style="width:50px;">
              </picture>
              <picture>
                <source srcset="static/assets/images/logo.webp" type="image/webp">
                <source srcset="static/assets/images/logo.png" type="image/png">
                <img src="static/assets/images/logo.webp" alt="Logo 12 RPL 1" class="mr-3" style="width:50px;">
              </picture>
              <p class="mb-0 text-small pt-1">© 2018-2021 Powered By XII RPL 1</p>
              <p class="text-small">Made With <i class="text-danger mdi mdi-heart"></i> From <a
                  class="text-small text-white mx-2 footer-link" href="https://facebook.com/fkhairulshaleh2"
                  target="_blank">Fikri Khairul Shaleh</a></p>
            </div>
          </div>
        </div>
      </footer>
    </div>
</template>
